trigger:  
      - main  

pool:  
  vmImage: 'ubuntu-latest'  

steps:  
- script: |  
       
          $apiUrl = "https://apilist.fun/api/food-api"    
          $apiResponse = Invoke-RestMethod -Uri $apiUrl -Method Get  
          echo $($apiResponse.StatusCode)"   
          echo $apiResponse  
  displayName: 'sample'