trigger:  
      - main  

pool:  
  vmImage: 'ubuntu-latest'  

steps:  
- script: |  
      try {  
          $apiUrl = "https://apilist.fun/api/food-api"  .
          Write-Output "API URL: $apiUrl"  
          $apiResponse = Invoke-RestMethod -Uri $apiUrl -Method Get  
          Write-Output "Status Code: $($apiResponse.StatusCode)"  
          Write-Output "API data received:" 
          Write-Output $apiResponse  
      } 
      catch {  
          Write-Error "Failed to retrieve API data. Error: $_"  
      }