trigger:  
      - main  

pool:  
  vmImage: 'ubuntu-latest'  

steps:  
- script: |  
       
          $apiUrl = "https://apilist.fun/api/food-api"    
          $apiResponse = Invoke-RestMethod -Uri $apiUrl -Method Get  
          echo $($apiResponse.StatusCode)"  
          Write-Output "API data received:" 
          Write-Output $apiResponse  
      